# Generated by Django 6.0.7 on 2026-07-14 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_remove_databaseconnection_password_and_more'),
        ('data_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractedrecord',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='extractionjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storedfile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='extractedrecord',
            name='is_edited',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='extractionjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='extractionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='file_format',
            field=models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('xlsx', 'Excel')], default='json', max_length=10),
        ),
        migrations.AddIndex(
            model_name='extractedrecord',
            index=models.Index(fields=['job', 'is_edited'], name='data_manage_job_id_d1e91c_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['owner', 'status'], name='data_manage_owner_i_417f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['owner', 'created_at'], name='data_manage_owner_i_3f83fd_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['owner', 'created_at'], name='data_manage_owner_i_8e58df_idx'),
        ),
    ]
