# Generated by Django 6.0.3 on 2026-04-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseconnection',
            name='password',
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='_password',
            field=models.CharField(db_column='password', default='', max_length=512),
            preserve_default=False,
        ),
    ]
